name: build

on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request: { }
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dorg.gradle.logging.stacktrace=all -Dorg.gradle.daemon=true -Dhttp.keepAlive=false -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.net.http.retryPost=false -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  build:
    if: >-
      ${{
        (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
        || (github.event_name == 'push' && !contains(github.event.head_commit.message, '[push-back]') && !contains(github.event.head_commit.message, '[noci]') && !contains(github.event.head_commit.message, '[no-ci]'))
        || github.event_name != 'push'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{github.workflow}}-build-${{strategy.job-index||'0'}}-${{github.ref}}
      cancel-in-progress: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Validate Gradle Wrapper
      uses: Wandalen/wretry.action@v3.8.0
      with:
        action: gradle/actions/wrapper-validation@v5
        attempt_limit: 3
        attempt_delay: 5000
    - name: Setup Java 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
    - name: Cache Gradle
      id: cache-gradle
      uses: remal-github-actions/cache-gradle@main
      with:
        build-cache-for-branches-only: 'true'
    - name: Build
      run: |
        ./gradlew build
